apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ckb-mainnet-layer2
  namespace: layer2
spec:
  selector:
    matchLabels:
      app: ckb-mainnet-layer2
  serviceName: "ckb-mainnet-layer2"
  replicas: 2
  template:
    metadata:
      labels:
        app: ckb-mainnet-layer2
        #logging: "true"
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: ckb-mainnet-layer2
        image: "jiangxianliang/ckb-mini:v0.41.0"
        command:
        - bash
        - "-c"
        - |
          set -ex
          cd /var/lib/ckb
          #ckb init --chain mainnet --force
          ckb migrate --force
          ckb run
        #livenessProbe:
          #exec:
            #command:
            #- /bin/check-ckb
          #initialDelaySeconds: 30
          #periodSeconds: 30
          #failureThreshold: 10
        readinessProbe:
          exec:
            command:
            - /bin/check-ckb
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 10
        ports:
          - name: rpc
            containerPort: 8114
            protocol: "TCP"
          - name: websocket
            containerPort: 28114
            protocol: "TCP"
        volumeMounts:
          - name: data
            mountPath: /var/lib/ckb
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2
      resources:
        requests:
          storage: 100Gi
