apiVersion: v1
kind: Service
metadata:
  name: ckb-testnet-indexer-layer2-svc
  namespace: layer2
  labels:
    app: ckb-testnet-indexer-layer2-svc
spec:
  ports:
  - name: rpc
    port: 8116
    targetPort: 8116
    protocol: TCP
  type: ClusterIP
  selector:
    app: ckb-testnet-indexer-layer2

