apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ckb-testnet-indexer-layer2
  namespace: layer2
spec:
  selector:
    matchLabels:
      app: ckb-testnet-indexer-layer2
  serviceName: "ckb-testnet-indexer-layer2"
  replicas: 1
  template:
    metadata:
      labels:
        app: ckb-testnet-indexer-layer2
        #logging: "true"
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: ckb-testnet-indexer-layer2
        image: "jiangxianliang/ckb-indexer:0.2.0"
        command:
        - bash
        - "-c"
        - |
          set -ex
          ckb-indexer -c http://ckb-testnet-layer2-svc:8114 -s /data -l 0.0.0.0:8116
        ports:
          - name: rpc
            containerPort: 8116
            protocol: "TCP"
        volumeMounts:
          - name: data
            mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2
      resources:
        requests:
          storage: 50Gi
