apiVersion: v1
kind: Service
metadata:
  name: ckb-testnet-layer2-svc
  namespace: layer2
  labels:
    app: ckb-testnet-layer2-svc
spec:
  ports:
  - name: rpc
    port: 8114
    targetPort: 8114
    protocol: TCP
  type: ClusterIP
  selector:
    app: ckb-testnet-layer2

