apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dex-redis-pv-claim
  namespace: ckb-dex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
