apiVersion: v1
kind: Service
metadata:
  namespace: ckb-dex
  name: dex-redis
  labels:
    app: dex-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: dex-redis
