apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ckb-testnet-staging
  namespace: staging
spec:
  selector:
    matchLabels:
      app: ckb-testnet-staging
  serviceName: "ckb-testnet"
  replicas: 2
  template:
    metadata:
      labels:
        app: ckb-testnet-staging
        logging: "true"
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: ckb-testnet-staging
        image: "jiangxianliang/ckb-mini:v0.37.0"
        command:
        - bash
        - "-c"
        - |
          set -ex
          cd /var/lib/ckb
          #ckb init --chain testnet --force
          ckb run
        ports:
          - name: rpc
            containerPort: 8114
            protocol: "TCP"
          - name: websocket
            containerPort: 28114
            protocol: "TCP"
        volumeMounts:
          - name: data
            mountPath: /var/lib/ckb
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2
      resources:
        requests:
          storage: 50Gi
