apiVersion: v1
kind: Service
metadata:
  name: ckb-testnet-staging-svc
  namespace: staging
  labels:
    app: ckb-testnet-staging-svc
spec:
  ports:
  - name: rpc
    port: 8114
    targetPort: 8114
    protocol: TCP
  - name: websokcet
    port: 28114
    targetPort: 28114
    protocol: TCP
  type: ClusterIP
  selector:
    app: ckb-testnet-staging

