apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-nas-subpath-k8s
mountOptions:
- nolock,tcp,noresvport
- vers=3
parameters:
  volumeAs: subpath
  server: "99c954922a-djv62.cn-zhangjiakou.nas.aliyuncs.com:/k8s"
provisioner: nasplugin.csi.alibabacloud.com
reclaimPolicy: Retain
