apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-nas-subpath-cita
mountOptions:
- nolock,tcp,noresvport
- vers=3
parameters:
  volumeAs: subpath
  server: "99c954922a-djv62.cn-zhangjiakou.nas.aliyuncs.com:/cita"
provisioner: nasplugin.csi.alibabacloud.com
reclaimPolicy: Retain
