apiVersion: v1
kind: Service
metadata:
  name: cita-jsonrpc-service
  namespace: cita-chain 
spec:
  selector:
    app: cita-node0 
  ports:
  - protocol: TCP
    port: 1337
    nodePort: 31337
    targetPort: 1337
  type: NodePort
