apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alert-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
