apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-main-conf
  namespace: monitoring
data:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"
      "smtp_smarthost": 'smtp.163.com:465'
      "smtp_from": 'cryptape@163.com'
      "smtp_auth_username": 'cryptape@163.com'
      "smtp_auth_password": '*********'
      "smtp_require_tls": false
    templates:   
      - '/etc/alertmanager/config/*.tmpl'
    "inhibit_rules":
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "critical"
      "target_match_re":
        "severity": "warning|info"
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "warning"
      "target_match_re":
        "severity": "info"
    "receivers":
    - "name": "Default"
    - "name": "Warning"
      email_configs:
      - to: 'jiangxianliang@cryptape.com'
        send_resolved: true
        html: '{{ template "email.to.html" . }}' 
        headers: { Subject: " {{ .CommonLabels.instance }} {{ .CommonLabels.pod }} {{ .CommonAnnotations.summary }}" }   
    - "name": "Watchdog"
    - "name": "Critical"
      email_configs:
      - to: 'jiangxianliang@cryptape.com'
        send_resolved: true
    "route":
      "group_by": ['namespace','alertname']
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "Default"
      "repeat_interval": "6h"
      "routes":
      - "match":
          "alertname": "Watchdog"
        "receiver": "Watchdog"
      - "match":
          "severity": "critical"
        "receiver": "Critical"
      - "match":
          "severity": "warning"
        "receiver": "Warning"
  email.tmpl: |-
    {{ define "email.to.html" }}
    {{- if gt (len .Alerts.Firing) 0 -}}
    {{ range .Alerts }}
    <pre>
    ========start==========
    告警程序: prometheus_alert <br>
    告警级别: {{ .Labels.severity }} <br>
    告警类型: {{ .Labels.alertname }} <br>
    故障主机: {{ .Labels.instance }} <br>
    告警主题: {{ .Annotations.summary }}  <br>
    告警内容: {{ .Annotations.description }}  <br>
    触发时间: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }} <br>
    ========end============
    </pre>
    {{ end }}{{ end -}}

    {{- if gt (len .Alerts.Resolved) 0 -}}
    {{ range .Alerts }}
    <pre>
    ========start==========
    告警程序: prometheus_alert <br>
    告警级别: {{ .Labels.severity }} <br>
    告警类型: {{ .Labels.alertname }} <br>
    故障主机: {{ .Labels.instance }} <br>
    告警主题: {{ .Annotations.summary }} <br>
    告警内容: {{ .Annotations.description }} <br>
    触发时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }} <br>
    恢复时间: {{ (.EndsAt.Add 28800e9).Format "2006-01-02 15:04:05" }} <br>
    <pre>
    ========start==========
    {{ end }}{{ end -}}
    {{- end }}
