apiVersion: v1
kind: Service
metadata:
  name: dex-mysql
  namespace: ckb-dex
spec:
  #type: ClusterIP       
  type: NodePort       
  ports:
  - name: mysql-port
    port: 3306
    targetPort: 3306
    nodePort: 30036
    protocol: TCP
    #clusterIP:   
  selector:
    app: dex-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex-mysql
  namespace: ckb-dex
spec:
  selector:
    matchLabels:
      app: dex-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dex-mysql
    spec:
      containers:
      - image: mysql:5.7
        name: dex-mysql
        args: ["--character-set-server", "utf8mb4", "--collation-server", "utf8mb4_unicode_ci", "--transaction-isolation", "READ-COMMITTED"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mMAyPTo3zfBXyumckb
        - name: TZ
          value: "Asia/Shanghai"
        ports:
        - containerPort: 3306
          name: dex-mysql
        volumeMounts:
        - name: mysql-persistent-storage
          subPath: dex-mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: dex-mysql-pv-claim
