apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: amm-redis
  namespace: ckb-amm
spec:
  serviceName: amm-redis
  replicas: 1
  selector:
    matchLabels:
      app: amm-redis
  template:
    metadata:
      labels:
        app: amm-redis
    spec:
      containers:
      - name: amm-redis
        image: jiangxianliang/redis:5.0.7
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 0.5
            memory: 500Mi
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: amm-redis-pv-claim
