apiVersion: v1
kind: Service
metadata:
  namespace: ckb-amm
  name: amm-redis
  labels:
    app: amm-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: amm-redis
