---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gw-testnet-monitor-readonly
  namespace: gw-testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gw-testnet-monitor-readonly
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gw-testnet-monitor-readonly
    spec:
      containers:
        - name: gw-testnet-monitor-readonly
          image: 'magicalne/godwoken-metrics-agent:version1.10.7'
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: WEB3_URL
              value: 'http://v1.testnet.godwoken.io/rpc'
            - name: GW_RPC_URL
              value: 'http://gw-testnet-svc-readonly:8119'
            - name: CKB_RPC_URL
              value: 'http://gw-testnet-ckb-svc:8114'
            - name: CKB_INDEXER_URL
              value: 'http://gw-testnet-ckb-indexer-svc:8116'
            - name: NET_ENV
              value: testnet_v1_1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        godwoken: testnet
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600