---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: gw-testnet-fullnode
  namespace: gw-testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gw-testnet-fullnode
      logging: 'true'
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gw-testnet-fullnode
        logging: 'true'
    spec:
      volumes:
        - name: godwoken-testnet-conf
          configMap:
            name: godwoken-testnet-conf-v1-fullnode
            defaultMode: 420
        - name: godwoken-testnet-db-conf
          configMap:
            name: godwoken-testnet-db-conf-v1-fullnode
            defaultMode: 420
        - name: godwoken-testnet-pk
          configMap:
            name: pk
            defaultMode: 420
        - name: godwoken-testnet-withdrawal-pk
          configMap:
            name: withdrawal-unlocker-key
            defaultMode: 420
      initContainers:
        - name: setsysctl
          image: busybox
          command:
            - sh
            - '-c'
            - |
              sysctl -w net.core.somaxconn=1024
              sysctl -w net.ipv4.tcp_tw_reuse=1
              sysctl -w net.ipv4.tcp_max_tw_buckets=4096
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
      containers:
        - name: gw-testnet-fullnode
          image: 'ghcr.io/godwokenrises/godwoken-prebuilds:1.7.1-poly1.5.0'
          command:
            - bash
            - '-c'
            - |
              set -ex
              exec godwoken run -c /deploy/config.toml
          ports:
            - name: rpc
              containerPort: 8119
              protocol: TCP
          env:
            - name: RUST_BACKTRACE
              value: '1'
            - name: RUST_LOG
              value: >-
                info,gw_generator=debug,gw_chain=info,gw_block_producer=info,gw_mem_pool=debug,gw_rpc_client=info
            - name: SMOL_THREADS
              value: '12'
            - name: BLOCKING_MAX_THREADS
              value: '16'
            - name: OTEL_BSP_MAX_EXPORT_BATCH_SIZE
              value: '25'
            - name: GODWOKEN_THREADS
              value: '8'
          resources:
            limits:
              memory: 8Gi
            requests:
              memory: 2Gi
          volumeMounts:
            - name: godwoken-testnet-conf
              readOnly: true
              mountPath: /deploy/config.toml
              subPath: config.toml
            - name: godwoken-testnet-pk
              readOnly: true
              mountPath: /deploy/pk
              subPath: pk
            - name: godwoken-testnet-withdrawal-pk
              readOnly: true
              mountPath: /deploy/withdrawal_unlocker_key
              subPath: withdrawal_unlocker_key
            - name: godwoken-testnet-db-conf
              readOnly: true
              mountPath: /deploy/db.toml
              subPath: db.toml
            - name: gw-data
              mountPath: /mnt
              subPath: ckb-testnet-godwoken-v1-db-fullnode
          livenessProbe:
            httpGet:
              path: /livez
              port: 8119
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 30
          readinessProbe:
            exec:
              command:
                - sh
                - /bin/gw-healthcheck.sh
            initialDelaySeconds: 6
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: jaeger-agent
          image: 'jaegertracing/jaeger-agent:1.32'
          args:
            - '--agent.tags=node=v1fullnode'
          env:
            - name: REPORTER_GRPC_HOST_PORT
              value: '192.168.62.240:8201'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        godwoken: testnet
      securityContext: {}
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: gw-data
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 150Gi
        storageClassName: ebs-sc
        volumeMode: Filesystem
      status:
        phase: Pending
  serviceName: gw-testnet-fullnode
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10