apiVersion: v1
kind: Service
metadata:
  name: amm-mysql
  namespace: ckb-amm
spec:
  #type: ClusterIP       
  type: NodePort       
  ports:
  - name: mysql-port
    port: 3306
    targetPort: 3306
    nodePort: 30037
    protocol: TCP
    #clusterIP:   
  selector:
    app: amm-mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: amm-mysql
  namespace: ckb-amm
spec:
  serviceName: amm-mysql
  replicas: 1
  selector:
    matchLabels:
      app: amm-mysql
  template:
    metadata:
      labels:
        app: amm-mysql
    spec:
      containers:
      - image: mysql:5.7
        name: amm-mysql
        args: ["--max-connections", "1000", "--character-set-server", "utf8mb4", "--collation-server", "utf8mb4_unicode_ci", "--transaction-isolation", "READ-COMMITTED"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mMAyPTo3zfBXyumjxlCHlXXnxs
        - name: TZ
          value: "Asia/Shanghai"
        ports:
        - containerPort: 3306
          name: amm-mysql
        volumeMounts:
        - name: mysql-persistent-storage
          subPath: amm-mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: amm-mysql-pv-claim
