apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: michi-ckb-testnet-pvc
  namespace: michi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
