---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-logging
  namespace: axon
  labels:
    k8s-app: elasticsearch-logging
data:
  elasticsearch.yml: |-
    network.host: 0.0.0.0
    xpack.security.enabled: true

