---
kind: Service
apiVersion: v1
metadata:
  name: gw-testnet-ckb-svc
  namespace: gw-testnet
  labels:
    app: gw-testnet-ckb-svc
spec:
  ports:
    - name: rpc
      protocol: TCP
      port: 8114
      targetPort: 8114
  selector:
    app: gw-testnet-ckb
  type: ClusterIP