apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckb-testnet-godwoken-1
  namespace: layer2
spec:
  selector:
    matchLabels:
      app: ckb-testnet-godwoken-1
  replicas: 1
  template:
    metadata:
      labels:
        app: ckb-testnet-godwoken-1
        svc: ckb-testnet-godwoken
        logging: "true"
    spec:
      containers:
      - name: ckb-testnet-godwoken-1
        image: "jjy0/godwoken-prebuilds:testnet"
        command:
        - bash
        - "-c"
        - |
          set -ex
          godwoken run -c /deploy/config.toml
        env:
        - name: RUST_BACKTRACE
          value: "1"
        - name: RUST_LOG
          value: "info"
        ports:
          - name: rpc
            containerPort: 8119
            protocol: "TCP"
        volumeMounts:
          - name: godwoken-testnet-conf
            mountPath: /deploy/config.toml
            subPath: config.toml
            readOnly: true
          - name: godwoken-testnet-pk
            mountPath: /deploy/pk
            subPath: pk
            readOnly: true
      volumes:
      - name: godwoken-testnet-conf
        configMap:
          name: godwoken-testnet-conf-1
      - name: godwoken-testnet-pk
        configMap:
          name: godwoken-testnet-pk-1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckb-testnet-godwoken-2
  namespace: layer2
spec:
  selector:
    matchLabels:
      app: ckb-testnet-godwoken-2
  replicas: 1
  template:
    metadata:
      labels:
        app: ckb-testnet-godwoken-2
        svc: ckb-testnet-godwoken 
        logging: "true"
    spec:
      containers:
      - name: ckb-testnet-godwoken-2
        image: "jjy0/godwoken-prebuilds:testnet"
        command:
        - bash
        - "-c"
        - |
          set -ex
          godwoken run -c /deploy/config.toml
        env:
        - name: RUST_BACKTRACE
          value: "1"
        - name: RUST_LOG
          value: "info"
        ports:
          - name: rpc
            containerPort: 8119
            protocol: "TCP"
        volumeMounts:
          - name: godwoken-testnet-conf
            mountPath: /deploy/config.toml
            subPath: config.toml
            readOnly: true
          - name: godwoken-testnet-pk
            mountPath: /deploy/pk
            subPath: pk
            readOnly: true
      volumes:
      - name: godwoken-testnet-conf
        configMap:
          name: godwoken-testnet-conf-2
      - name: godwoken-testnet-pk
        configMap:
          name: godwoken-testnet-pk-2



