kind: Service
apiVersion: v1
metadata:
  name: ckb-testnet-godwoken-svc
  namespace: layer2
spec:
  selector:
    #app: ckb-testnet-godwoken-1
    svc: ckb-testnet-godwoken
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8119
      targetPort: 8119
      nodePort: 30119

