apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: godwoken-logs-pvc
  namespace: layer2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
