apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: amm-mysql-exporter
  name: amm-mysql-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: mysql-metrics
  jobLabel: amm-mysql
  selector:
    matchLabels:
      k8s-app: amm-mysql-exporter
