apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: dex-redis-exporter
  name: dex-redis-exporter
  namespace: monitoring
spec:
  #type: NodePort
  ports:
  - name: http
    port: 9121
    #nodePort: 30019
    targetPort: http
  selector:
    k8s-app: dex-redis-exporter
