apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
