kind: Service
apiVersion: v1
metadata:
  name: staging-explorer-testnet-puma-svc
  namespace: staging
spec:
  selector:
    app: staging-explorer-testnet-puma
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
      nodePort: 30114
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-explorer-testnet-sidekiq
  namespace: staging
spec:
  selector:
    matchLabels:
      app: staging-explorer-testnet-sidekiq
  replicas: 1
  template:
    metadata:
      labels:
        app: staging-explorer-testnet-sidekiq
        logging: "true"
    spec:
      initContainers:
      - name: init-staging-explorer-testnet-conf
        image: 198023153192.dkr.ecr.ap-east-1.amazonaws.com/explorer:7b68c56f
        command: ["bash","entrypoint.sh"]
        args: ["init"]
        volumeMounts:
        - name: staging-explorer-testnet-conf
          mountPath: /config
          subPath: staging-explorer-testnet-config
      containers:
      - name: staging-explorer-testnet-sidekiq
        image: 198023153192.dkr.ecr.ap-east-1.amazonaws.com/explorer:7b68c56f
        resources:
          limits:
            memory: "2000Mi"
          requests:
            memory: "200Mi"
        command: ["bash","entrypoint.sh"]
        args: ["sidekiq"]
        volumeMounts:
        - name: staging-explorer-testnet-conf
          mountPath: /config
          subPath: staging-explorer-testnet-config
      volumes:
      - name: staging-explorer-testnet-conf
        persistentVolumeClaim:
          claimName: ckb-mainnet-staging-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-explorer-testnet-puma
  namespace: staging
spec:
  selector:
    matchLabels:
      app: staging-explorer-testnet-puma
  replicas: 1
  template:
    metadata:
      labels:
        app: staging-explorer-testnet-puma
        logging: "true"
    spec:
      containers:
      - name: staging-explorer-testnet-puma
        image: 198023153192.dkr.ecr.ap-east-1.amazonaws.com/explorer:7b68c56f
        command: ["bash","entrypoint.sh"]
        args: ["puma"]
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - name: staging-explorer-testnet-conf
          mountPath: /config
          subPath: staging-explorer-testnet-config
      volumes:
      - name: staging-explorer-testnet-conf
        persistentVolumeClaim:
          claimName: ckb-mainnet-staging-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-explorer-testnet-block-node-processor
  namespace: staging
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: staging-explorer-testnet-block-node-processor
  replicas: 1
  template:
    metadata:
      labels:
        app: staging-explorer-testnet-block-node-processor
        logging: "true"
    spec:
      containers:
      - name: staging-explorer-testnet-block-node-processor
        image: 198023153192.dkr.ecr.ap-east-1.amazonaws.com/explorer:7b68c56f
        command: ["bash","entrypoint.sh"]
        args: ["block_node_processor"]
        ports:
        volumeMounts:
        - name: staging-explorer-testnet-conf
          mountPath: /config
          subPath: staging-explorer-testnet-config
      volumes:
      - name: staging-explorer-testnet-conf
        persistentVolumeClaim:
          claimName: ckb-mainnet-staging-pvc

