apiVersion: apps/v1
kind: Deployment
metadata:
  name: amm-swap-matcher-dai-ckb
  namespace: ckb-amm
spec:
  selector:
    matchLabels:
      app: amm-swap-matcher-dai-ckb
  replicas: 1
  template:
    metadata:
      labels:
        app: amm-swap-matcher-dai-ckb
        logging: "true"
    spec:
      containers:
        - name: amm-swap-matcher-dai-ckb
          image: 198023153192.dkr.ecr.ap-east-1.amazonaws.com/glia-swap-matcher:tag
          command: ["npm","run","start:dai:dev"]
          ports:
          - name: http
            containerPort: 8080
          volumeMounts:
          - name: amm-swap-matcher-dai-ckb-conf
            mountPath: /app/configs/ckDAI-Ckb.env
            subPath: ckDAI-Ckb.env
            readOnly: true
      volumes:
      - name: amm-swap-matcher-dai-ckb-conf
        configMap:
          name: amm-swap-matcher-dai-ckb-env


