apiVersion: apps/v1
kind: Deployment
metadata:
  name: amm-swap-matcher-eth-ckb
  namespace: ckb-amm
spec:
  selector:
    matchLabels:
      app: amm-swap-matcher-eth-ckb
  replicas: 1
  template:
    metadata:
      labels:
        app: amm-swap-matcher-eth-ckb
        logging: "true"
    spec:
      containers:
        - name: amm-swap-matcher-eth-ckb
          image: 198023153192.dkr.ecr.ap-east-1.amazonaws.com/glia-swap-matcher:tag
          command: ["npm","run","start:eth:dev"]
          ports:
          - name: http
            containerPort: 8080
          volumeMounts:
          - name: amm-swap-matcher-eth-ckb-conf
            mountPath: /app/configs/ckETH-Ckb.env
            subPath: ckETH-Ckb.env
            readOnly: true
      volumes:
      - name: amm-swap-matcher-eth-ckb-conf
        configMap:
          name: amm-swap-matcher-eth-ckb-env


