apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ckb-mainnet-staging-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
