apiVersion: v1
kind: PersistentVolume
metadata:
  name: ckb-mainnet-staging-pv
  namespace: staging
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-edevv20
