apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fb-testnet-pvc
  namespace: fb-testnet
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
