apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dex-ckb-testnet-pvc
  namespace: ckb-dex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
